### ISSUE TITLE
SteemAuto Improvement Suggestion - Add Global Pause Function 

### ISSUE THREAD

**Issue by eastmaels** [mahdiyari/steemauto#1]
Originally copied from [here](https://utopian.io/utopian-io/@cryptogee/steemauto-improvement-suggestion-add-global-pause-function)

![SteemAuto fan follower homepage_720.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512473856/ho6pwyypgvp5iive5rkf.jpg)

This is a suggestion to add a global pause button to the excellent SteemAuto tool by @mahdiyari; particularly in regard to the fan follower function.

The reason for this is that a user may want to pause all voting activities to allow their voting weight to return to 100%, which currently takes 3 days. Or they may want to manual vote for a while, plus I'm sure many other reasons.

A global pause button would allow the user to pause voting for all Steemians they are following. The pause function would not interfere with a user's ability to follow new Steemians, however it would mean that any new additions to the follower list would also be paused, until the user deactivated it.

Therefore there are two possible solutions, one more complex and time consuming than the other, however for now we will focus on the simple solution of a global pause button.

>*Disclaimer: I am a novice coder therefore I will not speak in specifics. Any coding suggestions I make should be checked and verified before acting upon.

## SteemAuto Global Pause Function

![SteemAuto Cryptogee fan follower list__DISABLE_720.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512474796/zcygytvc9t8q2g7sobop.jpg)

I'm imaging that each name you choose to follow is called upon by a *this* and *name* functions within a variable (*var*). Therefore I assume that all followed accounts can be put in a master *var* called something along the lines of 

>var = this.name_ALL 

We can then hand it an *if, else* command to return true.

if ALL == (followed)
    return: true
else

Once we've done this we can create our pause function by calling upon the function which handles the voting permission. This of already exists as it is possible to disable and enable individual followings from within the settings.

![SteemAuto Cryptogee fan follower list_ENABLE_720.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512476103/xpohx5tq0rnsrqq1wv5u.jpg)

This is where my knowledge breaks down, however I'm imagining it shouldn't be too time consuming to set up an instance where the voting permission can be refused because a certain parameter is not met.

The code would allow the parameter to be met if a button was pressed.

The button on the site might look something like this

        <a href="#" class="btn btn-pause-global"><img src="resources/img/large-pause" alt="SteemAuto Large Pause Button"></a>

 .btn:link,
.btn:visited,
input[type=submit] {
}

### Multiple Pause Buttons

![SteemAuto Cryptogee fan follower list_pause_1_720.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512474842/fcx1swlptqoeupz4k74s.jpg)

The ideal scenario is to have multiple pause buttons, which in a way there already are.

When a user clicks settings next to an account they have followed. They can change voting weight, time of vote and either enable or disable the following. So the code already exists to effectively pause, as disabling does not effect follow status.

Therefore the only difference I'm proposing is to add a function for a small pause button to appear next to the name of each followed account, in order that following can be temporarily disabled without going into the settings.

This will provide a quick and easy way for a user to enable and disable voting. The global variable can be bypassed by giving the individual enable function the last word in the true/false statement.

Again the buttons on the site will look the same, just the class names and design parameters will differ.

     <a href="#" class="btn btn-pause"><img src="resources/img/small-pause" alt="SteemAuto Small Pause Button"></a>

.btn:link,
.btn:visited,
input[type=submit] { 
}

### Conclusion

In the end our ideal scenario would be this.
![SteemAuto Cryptogee fan follower list_ENABLEMANOVERRIDE_720.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512475962/ddjqahicwmfdaulw9htb.jpg)

Which gives us a global and individual pause/play  (disable/enable) function, meaning we can set local overrides to the global command should we wish.

Hopefully someone can pull this off, I myself wouldn't mind a try, however I am not experienced enough to go it alone and would need supervision from a more experienced developer.

I'm fully into the vibe of open source projects, and feel really excited to be involved in any way, however one of my ideas being implemented would really give me a kick!

I feel that the suggested changes will make for a more pleasant and smooth user experience, whilst also adding something to the look and feel of the site.

Oh and I must give credit to [this article](https://utopian.io/utopian-io/@eastmael/add-tags-filter-enable-disable-rule-and-change-default-wait-time-to-steemauto-s-fan-base) by my eSteemed colleague @eastmael, whereby he suggests a checkbox next to the enabled status on the followers. 

Any comments and critiques are very welcome, just let me know below.

>*Disclaimer: I am a novice coder therefore I will not speak in specifics. Any coding suggestions I make should be checked and verified before acting upon.

[*Cryptogee*](https://steemit.com/@cryptogee)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@cryptogee/steemauto-improvement-suggestion-add-global-pause-function">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mahdiyari** [comment]
Thanks,
I will work on that.
ps: users can pause all upvotes by increasing voting power limit.
