### ISSUE TITLE
Proposal to Draft a Privacy Policy for Steemauto

### ISSUE THREAD

**Issue by Pope19** [mahdiyari/steemauto#15]
In light of recent development and improvement with respect to Steemauto.com website, i decided to navigate the homepage in order to familiarize myself with the new changes.

Having done this, i discovered there wasn't a Privacy Policy either on the homepage or after logging into the website.

Therefore, as a Steemauto member, i decided to contribute my part using my copy-writing skills by creating a privacy policy for Steemauto.com.

Please, your response in this regard is highly anticipated.

@pope1995

**Comment by Pope19** [comment]
Thanks for your response.

[Here is the Link to the Steemauto Privacy Policy](https://www.dropbox.com/s/gwf6w2mx1shl3h8/Steemauto%20privacy%20policy.docx?dl=0).

You can edit, add or remove any part as you deem fit.

Your suggestions and Criticisms are welcomed.

@pope1995

**Comment by Vishalsingh4997** [comment]
Add a line, that "Steemauto does not hold any authority or control over any Third party apps (Like steemconnect client). Any changes regarding the third party apps can reflect in our system too."

**Comment by Pope19** [comment]
@Vishalsingh4997 

The Line have been added. [See link here](https://paper.dropbox.com/doc/STEEMAUTO-PRIVACY-POLICY-sSnIeC6t18fGMGhYfgEdk).

Document was created using Dropbox Paper Doc which you can edit.

Thank you.

**Comment by mahdiyari** [comment]
Thanks. Merged.
